export const sampleData = {
	login: "Hunor64",
	id: 61747377,
	node_id: "MDQ6VXNlcjYxNzQ3Mzc3",
	avatar_url: "https://avatars.githubusercontent.com/u/61747377?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/Hunor64",
	html_url: "https://github.com/Hunor64",
	followers_url: "https://api.github.com/users/Hunor64/followers",
	following_url:"https://api.github.com/users/Hunor64/following{/other_user}",
	gists_url: "https://api.github.com/users/Hunor64/gists{/gist_id}",
	starred_url: "https://api.github.com/users/Hunor64/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/Hunor64/subscriptions",
	organizations_url: "https://api.github.com/users/Hunor64/orgs",
	repos_url: "https://api.github.com/users/Hunor64/repos",
	events_url: "https://api.github.com/users/Hunor64/events{/privacy}",
	received_events_url: "https://api.github.com/users/Hunor64/received_events",
	type: "User",
	user_view_type: "public",
	site_admin: false,
	name: "Hunor József Nagy",
	company: null,
	blog: "nhunor.com",
	location: "Hungary",
	email: null,
	hireable: true,
	bio: null,
	twitter_username: null,
	public_repos: 143,
	public_gists: 0,
	followers: 5,
	following: 11,
	created_at: "2020-03-03T15:09:27Z",
	updated_at: "2024-11-28T06:48:52Z",
}
